image: node:20

cache:
  paths:
    - backend/node_modules/

stages:
  - checks
  - test

before_script:
  - cd backend 
  - npm install

linting:
  stage: checks
  script:
    - npm run lint
  only:
    - main
    - merge_requests

typechecking:
  stage: checks
  script:
    - npm run tsc
  only:
    - main
    - merge_requests

tests:
  stage: test
  script:
    - npm run test -- --passWithNoTests
  only:
    - main
    - merge_requests